allMVC/demo.PL/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.BLL.Repo;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;

namespace demo.PL.Controllers
{
    public class DepartmentController : Controller
    {
        private IUnitOfWork _IUnitOfWork;
        public DepartmentController(IUnitOfWork UnitOfWork)
        {
            _IUnitOfWork=UnitOfWork;
        }
        public IActionResult Index()
        {
            var deparment = _IUnitOfWork.DepRepo.GetAll();
            return View(deparment);
        }
        [HttpGet]
        public IActionResult create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult create(Department department)
        {
            if(ModelState.IsValid)
            {
                _IUnitOfWork.DepRepo.Add(department);
                var count = _IUnitOfWork.complete();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(department);
        }
        
        public IActionResult details(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var department= _IUnitOfWork.DepRepo.Get(id);
            if(department == null)
            {
                return NotFound();
            }
            return View(department);
            
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var department = _IUnitOfWork.DepRepo.Get(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }
        [HttpPost]
        public IActionResult edit(Department department)
        {
            try
            {
            if (ModelState.IsValid)
            {
                 _IUnitOfWork.DepRepo.Update(department);
                    var count = _IUnitOfWork.complete();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty,ex.Message);
            }
            return View(department);
        }
        [HttpGet]
        public IActionResult delete(int id)
        {

            if (id == null)
            {
                return BadRequest();
            }
            var department = _IUnitOfWork.DepRepo.Get(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }
        [HttpPost]
        public IActionResult delete(Department department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _IUnitOfWork.DepRepo.Delete(department);
                    var count = _IUnitOfWork.complete();
                        return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(nameof(Index));
        }

    }
}

allMVC/demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using demo.PL.ViewModel;
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections;
using System.Collections.Generic;
using Demo.BLL.Interfaces;
using System.Reflection.Metadata;
using demo.PL.Helpers;
namespace demo.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private IUnitOfWork _UnitOfWork;
        private IMapper _Mapper;
        public EmployeeController(IUnitOfWork UnitOfWork, IMapper mapper)
        {
            _UnitOfWork = UnitOfWork;
            _Mapper = mapper;
        }
        public IActionResult Index(string nameEmp)
        {
            if (string.IsNullOrEmpty(nameEmp))
            {
                var deparment = _UnitOfWork.EmployeeRepo.GetAll();
                var mapped = _Mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(deparment);
                return View(mapped);
            }
            else
            {
                var emp= _UnitOfWork.EmployeeRepo.GetEmpByName(nameEmp);
                var mapped = _Mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(emp);
                return View(mapped);
            }
             
            
        }
        [HttpGet]
        public IActionResult create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult create(EmployeeViewModel Employee)
        {
            if (ModelState.IsValid)
            {
                Employee.ImageName =DocumentSetting.UploadFile(Employee.Image, "Images");
                var mapped = _Mapper.Map<EmployeeViewModel,Employee>(Employee);
                _UnitOfWork.EmployeeRepo.Add(mapped);
                _UnitOfWork.complete();
                return RedirectToAction(nameof(Index));
            }
            return View(Employee);
        }
        public IActionResult details(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var Employee = _UnitOfWork.EmployeeRepo.Get(id);
            var mapped = _Mapper.Map<Employee, EmployeeViewModel>(Employee);
            if (Employee == null)
            {
                return NotFound();
            }
            return View(mapped);

        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var Employee = _UnitOfWork.EmployeeRepo.Get(id);
            var mapped = _Mapper.Map<EmployeeViewModel>(Employee);
            if (Employee == null)
            {
                return NotFound();
            }
            return View(mapped);
        }
        [HttpPost]
        public IActionResult edit(EmployeeViewModel Employee)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    var mapped = _Mapper.Map<EmployeeViewModel, Employee>(Employee);
                    _UnitOfWork.EmployeeRepo.Update(mapped);
                    var count= _UnitOfWork.complete();
                    if (count > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(Employee);
        }
        [HttpGet]
        public IActionResult delete(int id)
        {

            if (id == null)
            {
                return BadRequest();
            }
            var Employee = _UnitOfWork.EmployeeRepo.Get(id);
            var mapped = _Mapper.Map<Employee, EmployeeViewModel>(Employee);
            if (Employee == null)
            {
                return NotFound();
            }
            return View(mapped);
        }
        [HttpPost]
        public IActionResult delete(EmployeeViewModel Employee)//HENA LEEH elid biigy bnull??
        {
            try
            {
                if (ModelState.IsValid) 
                {
                    var mapped = _Mapper.Map<EmployeeViewModel, Employee>(Employee);
                    _UnitOfWork.EmployeeRepo.Delete(mapped);
                    var count = _UnitOfWork.complete();
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(nameof(Index));
        }
    }
}

allMVC/demo.PL/Controllers/UserController.cs
using demo.PL.ViewModel;
using Demo.DAL.Migrations;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace demo.PL.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<ApplicationUser> userManager,RoleManager<IdentityRole> roleManager)
        {
             _userManager=userManager ;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index(string email)
        {
            List<UsersViewModel> user;
            if (string.IsNullOrEmpty(email))
            {

                user = await _userManager.Users.Select( x => new UsersViewModel()
                {
                    Id=x.Id,
                    Email = x.Email,
                    FName = x.Fname,
                    LName = x.Lname,
                    phoneNumber = x.PhoneNumber                  
                }).ToListAsync();
                return View(user);
            }
            else
            {
                var findedUser= await _userManager.Users.Where(u=>u.Email.Trim().ToLower().Contains(email.Trim().ToLower())).ToListAsync();
                if (findedUser != null)
                {
                    user = findedUser.Select(u => new UsersViewModel
                    {
                        Id = u.Id,
                        Email = u.Email,
                        FName = u.Fname,
                        LName = u.Lname,
                        phoneNumber = u.PhoneNumber
                    }).ToList();
                    return View(user);
                }
                else
                {
                    return View();
                }
            }

        }

        public async Task<IActionResult> details(string id)
        {
            if (id != null)
            {
                var user = await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    UsersViewModel result = new UsersViewModel()
                    {
                        Id = user.Id,
                        Email = user.Email,
                        LName = user.Lname,
                        phoneNumber = user.PhoneNumber,
                        FName = user.Fname,
                    };
                    return View(result);
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> update(string id)
        {
            if (id != null)
            {
                var user=await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    UsersViewModel update = new UsersViewModel()
                    {
                        Id=user.Id,
                        Email = user.Email,
                        LName = user.Lname,
                        FName=user.Fname,
                        phoneNumber=user.PhoneNumber,
                    };
                    return View(update);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> update(UsersViewModel model)
        {
            if (ModelState.IsValid)
            {
                var existingUser = await _userManager.FindByIdAsync(model.Id);

                if (existingUser != null)
                {
                    existingUser.Email = model.Email;
                    existingUser.Fname = model.FName;
                    existingUser.Lname = model.LName;
                    existingUser.PhoneNumber = model.phoneNumber;
                    existingUser.UserName = model.Email.Split("@")[0];
                    var updated= await _userManager.UpdateAsync(existingUser);
                if (updated.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }  
                }
                             
            }
            return View(model);
        }
        public async Task<IActionResult> delete(string id)
        {
            if (id != null)
            {
                var user=await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    var result=await _userManager.DeleteAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View();
        }
    }
}

allMVC/demo.PL/Views/Shared/AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <title>@ViewData["Title"] - demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/authstyle.css" rel="stylesheet" />
</head>
<body> 
        <div class="wrapper">
            @RenderBody();
        </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jsauth.js"></script>
    @await RenderSectionAsync("validationScription", required: false)
</body>
</html>

allMVC/demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="logOut">logOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/javascript.js"></script>
    @await RenderSectionAsync("validationScription",required:false)

</body>
</html>

allMVC/demo.PL/Views/Shared/_buttonsPartial.cshtml
@model int
<td>
    <a asp-action="details" asp-route-id="@Model" class="btn btn-primary d-flex justify-content-between align-items-center">
        <i class="fa-solid fa-circle-info mr-1"></i>details
    </a>
</td>
<td>
    <a asp-action="edit" asp-route-id="@Model" class="btn btn-success d-flex justify-content-between align-items-center"><i class="fa-solid fa-pen-nib mr-1"></i>update</a>
    </td>
<td>
    <a asp-action="delete" asp-route-id="@Model" class="btn btn-outline-danger d-flex justify-content-between align-items-center"><i class="fa-solid fa-trash mr-1"></i>delete</a>
    </td>